<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WreckMPExtendedSync</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <TargetFramework>net35</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>WreckMPExtendedSync</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="_backup\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="PlayMaker">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed\PlayMaker.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="WreckMP">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\WreckMP\WreckMP.dll</HintPath>
    </Reference>
    <Reference Include="MSCLoader">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed\MSCLoader.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\mysummercar_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="BetterCheatBox">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\My Summer Car\Mods\BetterCheatBox.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
